[colors]

#bg = #23252e
; bg = #252525
bg = #14181c
#fg = #f9f8fe
fg = #d6d6d6
red = #c76b6b
blue = #5cc0e0
green = #8fee96
yellow = #c9c9c9
gr = #7a8a99
#gr = #4e4e4e
white = #e6e6e6

[bar/example]
width = 100%
height = 18pt
radius = 0
bottom = false

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 0pt

padding-left = 0
padding-right = 0

module-margin = 0
offset-x = 10
offset-y = 10

border-size = 4pt
border-color = ${colors.bg}

font-0 = JetBrainsMono Nerd Font:style=Regular:size=10;2
font-1 = Symbols Nerd Font:style=Regular:size=10;2
font-2 = Symbols Nerd Font:style=Regular:size=17;3
font-3 = JetBrainsMono Nerd Font:style=Regular:size=12;2

; modules-left = sep cpu sep memory sep weather sep sep xwindow
; modules-center = xworkspaces
; modules-right = cmus sep sep pulseaudio sep1 xkeyboard  date sep powermenu_bottom sep
;
modules-left = sep xworkspaces 
modules-center = cmus 
modules-right = sep_arrow sep1 cpu sep1 sep_line_thin sep1 pulseaudio sep1 sep_line_thin sep1 battery sep1 sep_line_thin sep1 network sep1 sep_line_thin sep1 xkeyboard sep_line_thin date sep1 sep_arrow_right

dpi-x = 96
dpi-y = 96

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = bspwm


; tray-position = center
; tray-background = ${colors.bg}
; tray-offset-x = 124pt
; tray-padding = 5


[settings]
screenchange-reload = true
pseudo-transparency = true
; pseudo-transparency = true


[module/launch_bottom]
type = custom/script
exec = echo "󰣇"
click-left =  rofi -show drun -config .config/bspwm/themes/bspwm_city/rofi/menu_bottom.rasi -show-icons
label-foreground = ${colors.bg}
label-background = ${colors.fg}
label-font = 1

;
; [module/xworkspaces]
; type = internal/xworkspaces
;
; label-active = %name%
; label-active-foreground = ${colors.green}
; label-active-background = ${colors.bg}
; label-active-padding = 2
;
; label-occupied = %name%
; label-occupied-padding = 2
; label-occupied-foreground = ${colors.fg}
; label-occupied-background = ${colors.bg}
;
; label-urgent = %name%
; label-urgent-background = ${colors.red}
; label-urgent-padding = 2
;
; label-empty = %name%
; label-empty-foreground = ${colors.gr}
; label-empty-background = ${colors.bg}
; label-empty-padding = 2

[module/xworkspaces]
type = internal/xworkspaces

label-active = ●
label-active-foreground = ${colors.gr}
label-active-background = ${colors.bg}
label-active-padding = 1.5

label-occupied = ○
label-occupied-foreground = ${colors.fg}
label-occupied-background = ${colors.bg}
label-occupied-padding = 1.5

label-empty = ○
label-empty-foreground = ${colors.gr}
label-empty-background = ${colors.bg}
label-empty-padding = 1.5

label-urgent = ⚡
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.bg}
label-urgent-padding = 1.5


[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-maxlen = 30
label-empty = Empty
label-foreground = ${colors.fg}
label-background = ${colors.bg}

; [module/battery]
; type = internal/battery
; battery = BAT0
; adapter = AC
; full-at = 98
;
; format-charging = <label-charging>
; format-charging-foreground = ${colors.green}
; format-charging-background = ${colors.bg}
;
; format-discharging = <label-discharging>
; format-discharging-foreground = ${colors.fg}
; format-discharging-background = ${colors.bg}
;
; format-full = <label-full>
; format-full-foreground = ${colors.green}
; format-full-background = ${colors.bg}
;
; label-charging = 󱐋 %percentage%%
; label-discharging = 󰁹 %percentage%%
; label-full = 󰁹 %percentage%%

[module/battery]
type = internal/battery

; Укажите название вашей батареи. Узнать можно командой: ls /sys/class/power_supply/
battery = BAT0
adapter = ADP0

; Когда батарея считается "полной", если она не достигает 100%
full-at = 98

; Порог для предупреждения о низком заряде
low-at = 10

; Формат при разряде
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%

; Формат при зарядке
format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%

; Формат, когда батарея полностью заряжена
format-full = <ramp-capacity> <label-full>
label-full = Fully charged

; Текст и иконки для предупреждения о низком заряде
label-low = ⚠ LOW
animation-low-0 = ⚠
animation-low-1 = 🔋
animation-low-framerate = 500

; Иконки для разных уровней заряда
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Анимация во время зарядки
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

; Интервал обновления (в секундах)
interval = 5


; [module/backlight]
; type = internal/backlight
; card = intel_backlight
; ; или card = amdgpu_bl0
;
; format = <label>
; label = 󰃟 %percentage%%
; label-foreground = ${colors.fg}
; label-background = ${colors.bg}

; [module/backlight_main]
; type = custom/script
; exec = ~/.config/polybar/scripts/brightness.sh main
; interval = 1
; label = 󰃟 %output%%
; label-foreground = ${colors.fg}
; label-background = ${colors.bg}
; format = <label>
;
; click-left = ~/.config/polybar/scripts/brightness.sh main down
; click-right = ~/.config/polybar/scripts/brightness.sh main up
; scroll-up = ~/.config/polybar/scripts/brightness.sh main up
; scroll-down = ~/.config/polybar/scripts/brightness.sh main down

; [module/backlight_secondary]
; type = custom/script
; exec = ~/.config/polybar/scripts/brightness.sh secondary
; interval = 1
; label = 󱩎 %output%%
; label-foreground = ${colors.fg}
; label-background = ${colors.bg}
; format = <label>
;
; click-left = ~/.config/polybar/scripts/brightness.sh secondary down
; click-right = ~/.config/polybar/scripts/brightness.sh secondary up
; scroll-up = ~/.config/polybar/scripts/brightness.sh secondary up
; scroll-down = ~/.config/polybar/scripts/brightness.sh secondary down
;
; [module/backlight_secondary]
; type = custom/script
; exec = ~/.config/polybar/scripts/brightness.sh secondary
; interval = 1
; label = 󱩎 %output%
; label-foreground = ${colors.fg}
; label-background = ${colors.bg}
; format = <label>
;
; click-left = ~/.config/polybar/scripts/brightness.sh secondary down
; click-right = ~/.config/polybar/scripts/brightness.sh secondary up
; scroll-up = ~/.config/polybar/scripts/brightness.sh secondary up
; scroll-down = ~/.config/polybar/scripts/brightness.sh secondary down

[module/date]
type = internal/date
interval = 5
date =
date-alt = "%Y-%m-%d"
time = "%H:%M"
label =%date% %time%
label-foreground = ${colors.fg}
label-background = ${colors.bg}

;
; [module/weather]
; type = custom/script
; exec = /home/owl/.config/bspwm/themes/gawr_gura/scripts/weather.sh
; interval = 600
; format-prefix = " "
;
; format-prefix-foreground = ${colors.fg}
; format-prefix-background = ${colors.bg}
; label-foreground = ${colors.fg}
; label-background = ${colors.bg}


[module/cmus]
type = custom/script
exec = ~/.config/polybar/scripts/cmus.sh
exec-if = pgrep -x cmus
interval = 1

click-left = cmus-remote --pause
click-right = cmus-remote --play
scroll-up = cmus-remote --next
scroll-down = cmus-remote --prev

format-prefix = " "
format = <label>
label = %output%
label-maxlen = 40

format-prefix-foreground = ${colors.fg}
format-prefix-background = ${colors.bg}
label-foreground = ${colors.fg}
label-background = ${colors.bg}


 [module/alsa]
 type = internal/alsa

 master-soundcard = default
 speaker-soundcard = default
 headphone-soundcard = default

 master-mixer = Master
 interval = 5
 format-volume = <label-volume>

 format-volume-prefix = "  "
 format-volume-prefix-foreground = ${colors.fg}
 format-volume-prefix-background = ${colors.gr}

 label-volume = %percentage%%
 label-volume-foreground =${colors.fg}
 label-volume-background =${colors.bg}
 label-volume-padding = 1


[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.fg}
format-volume-prefix-background = ${colors.bg}

format-volume = <label-volume>
label-volume-foreground = ${colors.fg}
label-volume-background = ${colors.bg}
label-volume = %percentage%%

label-muted = 󰝟 muted
label-muted-foreground = ${colors.red}
label-muted-background = ${colors.bg}

; Иконки для разных уровней громкости
volume-0 = 󰸈
volume-1 = 󰕿
volume-2 = 󰖀
volume-3 = 󰕾

 [module/xkeyboard]
 type = internal/xkeyboard
 blacklist-0 = num lock
 blacklist-1 = caps lock

 label-layout = "%icon% "
 layout-icon-0 = us;US
 layout-icon-1 = ru;RU
 label-layout-foreground = ${colors.fg}
 label-layout-background = ${colors.bg}


[module/powermenu_bottom]
type = custom/script
exec = echo ""
click-left = ~/.config/polybar/scripts/powermenu.sh
label-foreground = ${colors.red}
label-background = ${colors.bg}


[module/memory]
type = internal/memory
interval = 2
label = %percentage_used:2%%
format-prefix =" "
format-prefix-foreground = ${colors.fg}
format-prefix-background = ${colors.bg}
label-foreground = ${colors.fg}
label-background = ${colors.bg}


[module/cpu]
type = internal/cpu
interval = 5
label = %percentage:2%%
format-prefix =""
format-prefix-foreground = ${colors.fg}
format-prefix-background = ${colors.bg}
label-foreground = ${colors.fg}
label-background = ${colors.bg}


 [module/cava]
 type = custom/script
 tail = true
 exec = ~/.config/bspwm/themes/gawr_gura/scripts/cava.sh
 format = <label>
 format-background = ${colors.gr}
 format-font = 2
 label = %output%
 format-padding = 1

 [module/sep]
 type = custom/text
 content = ___
 content-foreground = ${colors.bg}

 [module/sep1]
 type = custom/text
 content = _
 content-foreground = ${colors.bg}

 [module/sep2]
 type = custom/text
 content = __
 content-foreground = ${colors.bg}

[module/network]
type = internal/network
interface = wlp2s0
interval = 3

format-connected = <label-connected> 
format-disconnected = <label-disconnected>

label-connected = 󰤨 %essid% %signal%%
label-connected-foreground = ${colors.fg}
label-connected-background = ${colors.bg}

label-disconnected = 󰤮 Offline
label-disconnected-foreground = ${colors.red}
label-disconnected-background = ${colors.bg}


[module/sep_arrow]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_arrow_right]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_line]
type = custom/text
content = " ┃ "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_line_thin]
type = custom/text
content = " │ "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_nerd_arrow]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_nerd_arrow2]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_nerd_arrow3]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}

[module/sep_nerd_arrow4]
type = custom/text
content = "  "
content-foreground = ${colors.gr}
content-background = ${colors.bg}
